blank_issues_enabled: true
contact_links:
  - name: Andiacoin Core Security Policy
    url: https://github.com/andiacoin/andiacoin/blob/master/SECURITY.md
    about: View security policy
  - name: Andiacoin Core Developers
    url: https://andiacoincore.org
    about: Andiacoin Core homepage
